name: "CI"

on:
  push:
  pull_request:

jobs:
  test:
    name: "🧪 Test"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Node.js"
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node }}
      - name: "🧰 Install dependencies"
        run: yarn install
      - name: "🏗️ Build package"
        run: yarn build
      - name: "🧪 Run tests"
        uses: cypress-io/github-action@v2
        with:
          install: false
          wait-on: "http://localhost:3000"
          tag: node-${{ matrix.node }}
