name: "CI"

on:
  push:
  pull_request:

jobs:
  build:
    name: "🏗️ Build"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: "♻️ Cache dependencies"
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
      - name: "🧰 Install dependencies"
        run: yarn install
      - name: "🏗️ Build package"
        run: yarn build
  test:
    name: "🧪 Test"
    runs-on: ubuntu-20.04
    needs:
      - build
    strategy:
      matrix:
        node: [12, 14]
    env:
      REACT_APP_API_USERNAME: ${{ secrets.API_USERNAME }}
      REACT_APP_API_PASSWORD: ${{ secrets.API_PASSWORD }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: "♻️ Cache dependencies"
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
            build
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
      - name: "🧰 Install dependencies"
        run: yarn install
      - name: "🧪 Run Cypress tests"
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start
          wait-on: "http://localhost:3000"
      - name: "📤 Upload Cypress sceenshots"
        uses: actions/upload-artifact@v2.2.2
        if: failure()
        with:
          name: Cypress sceenshots
          path: cypress/screenshots
      - name: "📤 Upload Cypress videos"
        uses: actions/upload-artifact@v2.2.2
        if: always()
        with:
          name: Cypress videos
          path: cypress/videos
      - name: "📤 Upload test coverage"
        uses: actions/upload-artifact@v2.2.2
        with:
          path: coverage/
          name: Test coverage
      - name: "📤 Publish test coverage"
        uses: codecov/codecov-action@v1
